# Generated by Django 4.1.1 on 2022-09-16 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_album_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 13, 34, 21, 807967, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='album',
            name='preview',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
