# Generated by Django 4.1.1 on 2022-09-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_album_create_date_alter_album_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='create_date',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
