# Generated by Django 4.1.1 on 2022-09-16 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_album_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='preview',
            field=models.ImageField(upload_to='gallery/data/previews/'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/data/images/')),
                ('note', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='Дата добавления')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.album')),
            ],
        ),
    ]
