# Generated by Django 4.1.1 on 2022-09-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_author_tag_remove_photo_photo_photo_exif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asdasd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.album')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
