# Generated by Django 4.1.1 on 2022-09-16 16:10

from django.db import migrations, models
import django.db.models.deletion
import exiffield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_album_asd_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(null=True, verbose_name='Photo ID')),
                ('image', models.ImageField(upload_to='gallery/data/images/')),
                ('exif', exiffield.fields.ExifField(default={}, editable=False)),
                ('note', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='Дата добавления')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('albums', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.album')),
                ('authors', models.ManyToManyField(to='gallery.author')),
            ],
        ),
        migrations.DeleteModel(
            name='Asd',
        ),
    ]
