# Generated by Django 4.1.1 on 2022-09-16 16:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_photos_delete_asd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(null=True, verbose_name='Album ID')),
                ('is_public', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Число просмотров')),
                ('preview', models.ImageField(upload_to='gallery/data/previews/')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('last_updated', models.DateTimeField(verbose_name='Дата изменения')),
                ('authors', models.ManyToManyField(to='gallery.author')),
            ],
        ),
        migrations.AlterField(
            model_name='photos',
            name='albums',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.albums'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
